FROM python:3.11-slim

WORKDIR /app
COPY . /app/

RUN pip install --no-cache-dir fastapi uvicorn sqlmodel redis psycopg2-binary pydantic requests

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]